name: test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - swift:5.3-xenial
    container: ${{ matrix.image }}
    env:
      LOG_LEVEL: info
    steps:  
      - name: Checkout TinyGraphQL
        uses: actions/checkout@v2
      - name: Run base tests with Thread Sanitizer
        run: swift test --enable-test-discovery --sanitize=thread

  macOS_iOS:
    env:
      LOG_LEVEL: info
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Test (iOS)
        run: xcodebuild -scheme TinyGraphQL test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12'
      - name: Build and Test (macOS)
        run: swift test
